@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}
participant Actor
Actor -> AbstractApplicationContext : obtainFreshBeanFactory
activate AbstractApplicationContext
AbstractApplicationContext -> AbstractApplicationContext : refreshBeanFactory
activate AbstractApplicationContext
AbstractApplicationContext --> AbstractApplicationContext
deactivate AbstractApplicationContext
AbstractApplicationContext -> AbstractApplicationContext : getBeanFactory
activate AbstractApplicationContext
AbstractApplicationContext --> AbstractApplicationContext
deactivate AbstractApplicationContext
return
@enduml